version: "3"


services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./docker/mysql-init-files/:/docker-entrypoint-initdb.d:z
    restart: always
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=python_docker_db
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=python_docker_db_user
      - MYSQL_PASSWORD=python_docker_db_password
    ports:
      - "3406:3306"
    expose:
      - '3406'
    networks:
      - python_docker_networks
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

  web:
    image: python_docker_web:latest
    restart: always
    ports:
      - "8000:8000"
    networks:
      - python_docker_networks
    depends_on:
      - mysql

  nginx:
    image: python_docker_nginx:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - python_docker_networks
    depends_on:
      - web


networks:
  python_docker_networks:
    driver: bridge