FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf
COPY ./docker/default.conf /etc/nginx/conf.d/default.conf

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
